package com.lab.comparison;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;

/**
 * #444: Persisted comparison result entity.
 * Stores the full comparison output (operator-level + dimension-level vs%) as JSON.
 */
@Data
@Entity
@Table(name = "comparison_results")
@NoArgsConstructor
public class ComparisonResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Baseline report ID */
    @Column(name = "baseline_report_id", nullable = false)
    private Long baselineReportId;

    /** Comma-separated test report IDs */
    @Column(name = "test_report_ids", nullable = false, length = 512)
    private String testReportIds;

    /** Overall vs% (average of dimensions) */
    @Column(name = "overall_vs_pct")
    private Double overallVsPct;

    /** Dimension-level vs% as JSON: {"compute": 115.2, "memory": 95.6, ...} */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "dimension_vs_pcts", columnDefinition = "jsonb")
    private String dimensionVsPcts;

    /** Full operator-level comparison data as JSON */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "operator_comparisons", columnDefinition = "jsonb")
    private String operatorComparisons;

    /** Summary text generated by rules engine */
    @Column(name = "summary", columnDefinition = "text")
    private String summary;

    @Column(name = "created_by")
    private Long createdBy;

    @CreationTimestamp
    @Column(updatable = false)
    private Instant createdAt;
}
